theme: jekyll-theme-minimal
title: Are we still falling into the ozone hole?
subtitle: A a self learning visualisation approach to the silent ozone hole pitfalls.
author: Thomas Mandelz
simple_search: http://google.com/search
description: Test Test Test
